from datetime import datetime, timedelta
from ics import Calendar, Event
import io


def generate_timeline(scholarship: dict) -> bytes:
    """
    Takes a scholarship deadline and generates a .ics calendar file
    with 4 milestone events working backward from the deadline.
    Returns bytes — the file is never saved to disk.
    """
    deadline_str = scholarship.get("deadline", "")

    try:
        deadline = datetime.strptime(deadline_str, "%Y-%m-%d")
    except ValueError:
        deadline = datetime.now() + timedelta(days=30)

    milestones = [
        {
            "name": f"[{scholarship['name']}] Request recommendation letters",
            "date": deadline - timedelta(weeks=5),
            "description": (
                "Contact your professors or project advisers today "
                "to request recommendation letters. "
                "Give them at least 3 weeks."
            ),
        },
        {
            "name": f"[{scholarship['name']}] First essay draft due",
            "date": deadline - timedelta(weeks=3),
            "description": (
                "Complete your first full essay draft. "
                "Use the step-by-step guide generated by "
                "Scholarship Copilot as a reference."
            ),
        },
        {
            "name": (
                f"[{scholarship['name']}] "
                "Gather documents (transcript, IDs)"
            ),
            "date": deadline - timedelta(weeks=2),
            "description": (
                "Collect certified true copy of transcript, "
                "valid ID, and any other required documents."
            ),
        },
        {
            "name": (
                f"[{scholarship['name']}] Final review and submission"
            ),
            "date": deadline - timedelta(days=3),
            "description": (
                f"Final check of all documents before the hard "
                f"deadline: {deadline.strftime('%B %d, %Y')}. "
                "Submit at least 3 days early."
            ),
        },
    ]

    cal = Calendar()
    for m in milestones:
        e = Event()
        e.name = m["name"]
        e.begin = m["date"].strftime("%Y-%m-%d")
        e.description = m["description"]
        e.make_all_day()
        cal.events.add(e)

    buffer = io.StringIO()
    buffer.writelines(cal.serialize_iter())
    return buffer.getvalue().encode("utf-8")


def generate_application_steps(scholarship: dict) -> list[dict]:
    """
    Generates a step-by-step application checklist for a given
    scholarship, working backward from the deadline.
    Returns a list of step dicts — nothing is saved to disk.
    """
    deadline_str = scholarship.get("deadline", "")

    try:
        deadline = datetime.strptime(deadline_str, "%Y-%m-%d")
        deadline_display = deadline.strftime("%B %d, %Y")
        weeks_left = (deadline - datetime.now()).days // 7
        urgency = (
            "Urgent — less than 3 weeks left!"
            if weeks_left < 3
            else f"{weeks_left} weeks until deadline"
            if weeks_left < 6
            else f"{weeks_left} weeks until deadline — good time to start"
        )
    except ValueError:
        deadline_display = "Check official website"
        urgency = "Verify the deadline on the official website"

    steps = [
        {
            "number": 1,
            "title": "Verify your eligibility",
            "description": (
                f"Confirm you meet all requirements for "
                f"**{scholarship['name']}**. "
                f"Required GPA: **{scholarship['gpa_required'] or 'None stated'}**. "
                f"Eligible levels: **{', '.join(scholarship['level']).capitalize()}**. "
                f"Eligible majors: **{', '.join(scholarship['majors'])}**."
            ),
            "icon": "",
        },
        {
            "number": 2,
            "title": "Visit the official scholarship page",
            "description": (
                f"Go to [{scholarship['provider']}]({scholarship['link']}) "
                "and download the official application form and requirements "
                "checklist. Confirm the deadline and look for any additional "
                "eligibility conditions not listed here."
            ),
            "icon": "",
        },
        {
            "number": 3,
            "title": "Request recommendation letters",
            "description": (
                "Approach your professor, department head, or project "
                "adviser as soon as possible. Give them at least 3 weeks "
                "and provide them with a brief summary of the scholarship "
                "and why you are applying."
            ),
            "icon": "",
        },
        {
            "number": 4,
            "title": "Gather required documents",
            "description": (
                "Prepare your certified true copy of transcript of records, "
                "valid government-issued ID, certificate of enrollment, "
                "and any proof of income or family background if required "
                "by this scholarship."
            ),
            "icon": "",
        },
        {
            "number": 5,
            "title": "Write your application essay",
            "description": (
                f"Respond to the essay prompt: "
                f"*\"{scholarship['essay_prompt']}\"* "
                f"Ground your answer in the scholarship's core values: "
                f"{scholarship['core_values']}. "
                "Aim for 300–500 words and have someone review it before "
                "submitting."
            ),
            "icon": "",
        },
        {
            "number": 6,
            "title": "Submit your application",
            "description": (
                f"Hard deadline: **{deadline_display}**. "
                f"{urgency}. "
                "Submit at least 3 days before the deadline to allow "
                "time to resolve any technical issues or missing "
                "documents."
            ),
            "icon": "",
        },
    ]

    return steps