from datetime import datetime, timedelta
from ics import Calendar, Event
import io

def generate_timeline(scholarship: dict) -> bytes:
    """
    Takes a scholarship deadline and generates a .ics calendar file
    with 4 milestone events working backward from the deadline.
    Returns bytes — the file is never saved to disk.
    """
    deadline_str = scholarship.get("deadline", "")

    try:
        deadline = datetime.strptime(deadline_str, "%Y-%m-%d")
    except ValueError:
        deadline = datetime.now() + timedelta(days=30)

    milestones = [
        {
            "name": f"[{scholarship['name']}] Request recommendation letters",
            "date": deadline - timedelta(weeks=5),
            "description": "Contact your professors or project advisers today to request recommendation letters. Give them at least 3 weeks."
        },
        {
            "name": f"[{scholarship['name']}] First essay draft due",
            "date": deadline - timedelta(weeks=3),
            "description": "Complete your first full essay draft. Use the draft generated by Scholarship Copilot as a starting point."
        },
        {
            "name": f"[{scholarship['name']}] Gather documents (transcript, IDs)",
            "date": deadline - timedelta(weeks=2),
            "description": "Collect certified true copy of transcript, valid ID, and any other required documents."
        },
        {
            "name": f"[{scholarship['name']}] Final review and submission",
            "date": deadline - timedelta(days=3),
            "description": f"Final check of all documents before the hard deadline: {deadline.strftime('%B %d, %Y')}. Submit at least 3 days early."
        },
    ]

    cal = Calendar()
    for m in milestones:
        e = Event()
        e.name = m["name"]
        e.begin = m["date"].strftime("%Y-%m-%d")
        e.description = m["description"]
        e.make_all_day()
        cal.events.add(e)

    buffer = io.StringIO()
    buffer.writelines(cal.serialize_iter())
    return buffer.getvalue().encode("utf-8")